name: quran_exam_app
description: تطبيق اختبارات قالون - اختبار الآيات والتصنيفات
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  share_plus: ^7.2.0
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/categories.json
    - assets/subcategories.json
    - assets/topics.json
    - assets/questions.json
    - assets/chapters.json
    - assets/verses.json
    - assets/tafseer.json
    - assets/manifest.json